version: "3.8"

services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - "1080:1080"
    networks:
      - app-network

  db:
    container_name: postgresql
    image: postgres
    environment:
      POSTGRES_USER: ${JIRUSH_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${JIRUSH_DATABASE_PASSWORD}
      POSTGRES_DB: "jira"
    ports:
      - "5432:5432"
    restart: always
    networks:
      - app-network

  app:
    container_name: project-final
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      spring.datasource.username: "jira"
      spring.datasource.password: "JiraRush"
      spring.datasource.url: "jdbc:postgresql://db:5432/jira"

      GITHUB_CLIENT_ID: ${JIRUSH_GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${JIRUSH_GITHUB_CLIENT_SECRET}
      GOOGLE_CLIENT_ID: ${JIRUSH_GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${JIRUSH_GOOGLE_CLIENT_SECRET}
      GITLAB_CLIENT_ID: ${JIRUSH_GITLAB_CLIENT_ID}
      GITLAB_CLIENT_SECRET: ${JIRUSH_GITLAB_CLIENT_SECRET}
      GITLAB_REDIRECT_URI: ${JIRUSH_GITLAB_REDIRECT_URI}

      MAIL_USERNAME: ${JIRUSH_MAIL_USERNAME}
      MAIL_PASSWORD: ${JIRUSH_MAIL_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - nginx
      - db
    restart: always
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
